export const FETCH_USER_INFO_REQUEST = 'homeReducer/FETCH_USER_INFO_REQUEST';
export const FETCH_USER_INFO_SUCCESS = 'homeReducer/FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_INFO_FAILED = 'homeReducer/FETCH_USER_INFO_FAILED';

export const CREATE_CLASSROOM_REQUEST = 'homeReducer/CREATE_CLASSROOM_REQUEST';
export const CREATE_CLASSROOM_SUCCESS = 'homeReducer/CREATE_CLASSROOM_SUCCESS';
export const CREATE_CLASSROOM_FAILED = 'homeReducer/CREATE_CLASSROOM_FAILED';
export const CREATE_CLASSROOM_RESET = 'homeReducer/CREATE_CLASSROOM_RESET';

export const JOIN_CLASSROOM_REQUEST = 'homeReducer/JOIN_CLASSROOM_REQUEST';
export const JOIN_CLASSROOM_SUCCESS = 'homeReducer/JOIN_CLASSROOM_SUCCESS';
export const JOIN_CLASSROOM_FAILED = 'homeReducer/JOIN_CLASSROOM_FAILED';
export const JOIN_CLASSROOM_RESET = 'homeReducer/JOIN_CLASSROOM_RESET';