export const SUBMISSION_REQUEST = "homeworkReducer/SUBMISSION_REQUEST";
export const SUBMISSION_SUCCESS = "homeworkReducer/SUBMISSION_SUCCESS";
export const SUBMISSION_FAILED = "homeworkReducer/SUBMISSION_FAILED";
export const SUBMISSION_RESET = "homeworkReducer/SUBMISSION_RESET";
export const SUBMISSION_SEARCH = "homeworkReducer/SUBMISSION_SEARCH";

export const SUBMITHOMEWORK_DETAIL_REQUEST = "homeworkDetailReducer/SUBMITHOMEWORK_DETAIL_REQUEST";
export const SUBMITHOMEWORK_DETAIL_SUCCESS = "homeworkDetailReducer/SUBMITHOMEWORK_DETAIL_SUCCESS";
export const SUBMITHOMEWORK_DETAIL_FAILED = "homeworkDetailReducer/SUBMITHOMEWORK_DETAIL_FAILED";
export const SUBMITHOMEWORK_DETAIL_RESET = "homeworkDetailReducer/SUBMITHOMEWORK_DETAIL_RESET";