export const SUBMITHOMEWORK_REQUEST = "homeworkReducer/SUBMITHOMEWORK_REQUEST";
export const SUBMITHOMEWORK_SUCCESS = "homeworkReducer/SUBMITHOMEWORK_SUCCESS";
export const SUBMITHOMEWORK_FAILED = "homeworkReducer/SUBMITHOMEWORK_FAILED";
export const SUBMITHOMEWORK_RESET = "homeworkReducer/SUBMITHOMEWORK_RESET";
export const SUBMITHOMEWORK_SEARCH = "homeworkReducer/SUBMITHOMEWORK_SEARCH";

export const SUBMITHOMEWORK_DETAIL_REQUEST = "homeworkDetailReducer/SUBMITHOMEWORK_DETAIL_REQUEST";
export const SUBMITHOMEWORK_DETAIL_SUCCESS = "homeworkDetailReducer/SUBMITHOMEWORK_DETAIL_SUCCESS";
export const SUBMITHOMEWORK_DETAIL_FAILED = "homeworkDetailReducer/SUBMITHOMEWORK_DETAIL_FAILED";
export const SUBMITHOMEWORK_DETAIL_RESET = "homeworkDetailReducer/SUBMITHOMEWORK_DETAIL_RESET";